### ISSUE TITLE
working for new camera GS3-U3-41C6NIR-C?

### ISSUE THREAD

**Issue by neurochen** [oculomatic/oculomatic-release#1]
Thank you so much for sharing this great open-source eye tracker. I am trying to set it up in the lab. We already have a GS3-U3-41C6NIR-C camera, also from the Point Grey. Could it be working in principle with your software?

**Comment by thejanzimmermann** [comment]
Yes it should work just fine.
In mode 0 with 416 x 240 FOV you should be able to get about 686 FPS with that sensor.

**Comment by neurochen** [comment]
Thanks, Jan! I will try that out recently. Cheers.
