### ISSUE TITLE
opening the vc projects

### ISSUE THREAD

**Issue by neurochen** [oculomatic/oculomatic-release#2]
Hi, I want to modify the source code a little bit. After downloading the source code, I used visual studio 2015 to edit it. But it seems not able to load the projects correctly. Could you please guide me on how to modify the solution? Thanks.

**Comment by thejanzimmermann** [comment]
Hi,

That is likely caused by dependencies not being resolved correctly. Could
you tell me the error exactly ? Did you load the sln file or the project
file?

**Comment by neurochen** [comment]
Please see the screenshots below. I tried both sln and vcproj files, the results are the same. Thanks.
![0](https://cloud.githubusercontent.com/assets/10821596/25647268/945e5e08-2f8e-11e7-8f87-c7485fffa9eb.png)
![untitled](https://cloud.githubusercontent.com/assets/10821596/25647271/96fe8d54-2f8e-11e7-80ec-dbeb5089a415.png)

**Comment by neurochen** [comment]
oculomatic.vcxproj : error  : Unable to read the project file "oculomatic.vcxproj".
The imported project openFrameworksRelease.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
openframeworksLib.vcxproj : error  : Project openframeworksLib.vcxproj could not be found.

Uh, it's related to openframeworks. It 's my first having issues with lib dependents when loading the projects. I'll try to fix it first.

**Comment by thejanzimmermann** [comment]
Please check the readme and make sure all he dependencies are installed.

Let me know if you need help.

**Comment by neurochen** [comment]
What I am missing now is the files within the folder ofxDatGui\src\templates. I searched online, and it seems to be discontinued. Could you please send me your ofxDatGui at minggui.chen@gmail.com? Thanks.

**Comment by thejanzimmermann** [comment]
Just delete the ofxdatgui ref from the project. I only used it for a
voltage display that is currently not enabled anyhow.
