### ISSUE TITLE
Oculomatic and compatible cameras

### ISSUE THREAD

**Issue by MarcoUniPr** [oculomatic/oculomatic-release#3]
Hi, 
I am going to use Oculomatic as eyetracker for my future experiments. For your knowledge, can other cameras (eg. KYT-U400-MC S0550R01 330 fps USB 2.0) different from FLIR or Chamaleon being used with flycapture and oculomatic?  
Waiting a kind answer 
I wish good job
Best Regards
Marco

**Comment by thejanzimmermann** [comment]
Hi Marco,

You would have to recompile and use a different SDK if you switch to a different camera model.
It is fairly straightforward but requires some c++ understanding

Kind regards

Jan
